name: "WASM OJ Problem Box Manager"
description: "WASM OJ Problem Box Manager"
inputs:
    command:
        description: "Command to run"
        required: false
        default: "index"
runs:
    using: "docker"
    image: "docker://ghcr.io/wasm-oj/box"
    args:
        - ${{ inputs.command }}
